name: TradingView Live Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"  # har 5 minute me chalega

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install requests
      - run: python bot.py
