name: Binance Live Data Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # हर 5 मिनट पर चलेगा
  workflow_dispatch:       # Manual run भी possible

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Requests
        run: pip install requests

      - name: Run Bot
        run: python bot.py
